### ISSUE TITLE
Trezor detection

### ISSUE THREAD

**Issue by ondra-novak** [trezor/connect#8] opened 2015-10-26 21:33 UTC
Hi. I am just playing with trezor connect and there are few features I am missing. One of them is trezor detection. I want to show UI to user only if he/she can use the trezor. The feature can detect whether the bridge/extension is presented - this should be enough to achieve this requirement (user without the bridge probably hasn't the trezor at all).

Other missing features may appear in separate issues :)

Thank you!

**Comment by prusnak** [comment] 2018-05-23 18:38
Closed as duplicate of https://github.com/trezor/connect/issues/124

**Closed by prusnak** 2018-05-23 18:38 UTC
