### ISSUE TITLE
Can not sign Transaction with more then 20 BTC for PAYTOMULTISIG

### ISSUE THREAD

**Issue by nbphuoc** [trezor/connect#82] opened 2017-10-09 12:20 UTC
I got this error when attempting to sign a transaction which output has more than 21.48 BTC: 
```
Range Error: value out of range
```
I believe this is because 20 BTC = 2 billions satoshi and the maximum integer number is: 2,147,483,647
How do I fix this?

**Comment by runn1ng** [comment] 2017-10-09 13:55
Hm, this looks like it comes from some Javascript.

I don't know if the bug is in Connect or Extension though

To eliminate possibility that it's extension:

Do you use extension or bridge for transport? Does switching to the other
helps? Firefox / Chrome switch helps?

**Comment by prusnak** [comment] 2017-10-09 17:52
Also what service are you using Connect with?

**Comment by lionello** [comment] 2017-10-16 02:42
I'm running into the same issue when trying to transfer 5 BTC + 17 BTC change. I've debugged this with Chrome debugger and the inputs to signtx are correct, but the Trezor just comes back with RangeError.

**Comment by prusnak** [comment] 2017-10-16 11:48
I was able to reproduce the issue, @runn1ng and @szymonlesisz will look into that shortly.

**Comment by runn1ng** [comment] 2017-10-16 12:12
OK, we found the bug, it's actually not because of the BTC, but because of segwit transactions not being properly parsed (old bitcoinjs-lib). We are looking into it

**Comment by runn1ng** [comment] 2017-10-16 16:21
Can you try it again, with either v3 branch locally or on https://connect.trezor.io/3/ (or older versions)? It should be working now.

**Comment by lionello** [comment] 2017-10-17 07:17
Is there a fix for `trezord`? It seems to fail with similar error when converting JSON to protobuf.

**Comment by runn1ng** [comment] 2017-10-17 09:20
Is the error still hapenning with Trezor Connect?

**Comment by lionello** [comment] 2017-10-17 13:15
Changing to v3 fixed the issue! Could you share more info about the fix? Wondering whether trezord has the same or another issue.

**Comment by runn1ng** [comment] 2017-10-17 14:42
It was an issue with segwit. When sending from an account that had even 1 transaction with segwit inputs, it threw an error. We used old bitcoinjs-lib version, that didn't know how to parse segwit transactions. It is fixed now.

**Closed** 2017-11-20 16:32 UTC
