### ISSUE TITLE
pop up confirmation screen disappears in a few seconds - transaction fails 

### ISSUE THREAD

**Issue by BCLind** [trezor/connect#1017] opened 2022-01-13 16:54 UTC
Looking for help.  It just started a couple of days ago.  Using Metamask and the Trezor 1.  I can deposit to the hardware wallets and see the balances.  When I try to transfer, swap, or anything that requires my confirmation it fails.  I get the initial approval screen in Metamask for the gas and then for a second the tab opens starting the Trezor approval and it goes away.  I quickly go to History and reopen it up and it is the green circle of death "Loading".  That is as far as it goes and the transaction times our and fails.   I have made sure it is OK in my ad and pop-up blocker.  I made sure I am running the latest Bridge on the Trezor. 2.0.31  I am also not using the Phrase at this point as I say that was a possible issue on the Trezor help forum.  They sent me here for hopefully better answers.

I am at a loss on what to do next.  I am not a tech person.

I am running Chrome and everything is up to date; my Trezor is running the latest updates.

Please advise on the next best steps to try.

**Comment by inthernar** [comment] 2022-01-21 21:58
This may help: https://github.com/trezor/connect/issues/784#issuecomment-1011673699

**Comment by BCLind** [comment] 2022-01-21 22:15
Thank you for this.  I ended up deleting my whole metamask extension and rebuilding everything.  Pain in the butt, but it worked.  I do think it was something corrupt with the extension. 

Again thank you for looking into this for me.

**Comment by tsusanka** [comment] 2022-02-04 16:56
Duplicate of https://github.com/trezor/trezor-suite/issues/4888.

**Closed as completed by tsusanka** 2022-02-04 16:56 UTC
