### ISSUE TITLE
webusb/mobile support

### ISSUE THREAD

**Issue by losnappas** [trezor/connect#793] opened 2021-04-10 16:01 UTC
Hello,

Is it possible to use WebUSB to support mobile devices with trezor-connect? I have tried the following,

```ts
await TrezorConnect.init({
  manifest: {
    email: "example@example.com",
    appUrl: "localhost",
  },
  webusb: true,
})

const result = await TrezorConnect.ethereumGetPublicKey({
  path,
})
```

But that does not seem to work. Is this not supported on 3rd party websites? It seems to work on `wallet.trezor.io`, but I've found no other website so far.

**Comment by szymonlesisz** [comment] 2021-04-13 13:52
Hi @losnappas,
WebUsb implementation using popup  is currently broken since chrome 72. (except for web extensions)
Technically device needs to be paired with corelation of `connect.trezor.io` domain **and** the actual domain where connect is implemented.
For example pairing on `xyz.com + connect.trezor.io` is not the same as `other.com + connect.trezor.io`.
WebUsb button is served from connect.trezor.io and displayed in popup which is also served from connect.trezor.io (no corelation here).
Previous working solution allowed us to call "click" on the element WITHIN 3rd party website (click inside popup was actually clicking on [window.opener connect iframe](https://github.com/trezor/connect/blob/develop/src/js/popup/view/selectDevice.js#L21-L35)) but as i said, now it throws security error (justifiably, i think).

The only valid solution to this is to display WebUSB button within/above 3rd party website but this is currently not possible because actual connect UI is displayed in a new window.
We do have plans (with low priority) to split connect UI into 2 separated containers:
- displayed in iframe above 3rd party website (as a modal). this would render basic stuff, like "connect your device" (with webusb button) or "follow instructions/confirm"
- displayed in popup (new window/tab), for sensitive content like entering pin or passphrase

I'm leaving this issue opened for a reference

**Comment by tsusanka** [comment] 2022-02-04 16:32
I believe this is a duplicate of https://github.com/trezor/trezor-suite/issues/4865.

**Closed as completed by tsusanka** 2022-02-04 16:32 UTC
