### ISSUE TITLE
Stellar Change Trust-type transactions fail, missing destination

### ISSUE THREAD

**Issue by lordcase** [trezor/connect#273] opened 2018-12-02 23:11 UTC
I have managed to make signing transactions work, but only if it's a send type transaction.
If I want to create change trust type (to accept a certain kind of asset, for example) I get an ""Invalid destination account" error.
Which is a problem, as these transactions do not need a destination address, as far as I know.
I have tried passing the source address as destination, but that does not work either.

Any ideas?

**Comment by prusnak** [comment] 2018-12-03 13:30
cc @tsusanka

**Comment by prusnak** [comment] 2018-12-03 13:31
Maybe a duplicate of https://github.com/trezor/trezor-core/issues/421

**Comment by lordcase** [comment] 2018-12-03 13:35
Thanks @prusnak, it very well might be a duplicate.
In the other issue I have not seen mentioned that sending to trezor without destination already produces an error, that might be extra info that can help (or it can be a separate issue).
Did not think to look under Core, thx!

**Comment by tsusanka** [comment] 2018-12-03 15:57
I think this is probably a Connect's issue, because firmware does not require destination in the `StellarChangeTrustOp`.

**Comment by szymonlesisz** [comment] 2018-12-03 16:20
Im pretty sure that there is no validation of transaction fields inside connect. And it doesn't send "destination" field in this type of tx. See here:
https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/stellarSignTx.js#L160-L166

Connect does some params type validation before, but every error begins with "Invalid params: ...." string

**Comment by tsusanka** [comment] 2018-12-03 18:57
Hm I'll have another look then. @lordcase could you confirm this is a firmware error? Connect should say so.

Also you could you provide the exact input you're using? Or even more details how you are testing this? In other words, the more info you give the more I appreciate it :)

**Comment by lordcase** [comment] 2018-12-04 00:05
Ok, so first of all, the error payload i get is: 
error: "Invalid destination account",
code: "Failure_ProcessError"

**Comment by lordcase** [comment] 2018-12-04 00:11
Our project is adding trezor support to the stellarterm app. I have managed to insert the login and sign functions successfully sofar. 
Otherwise the app functions perfectly, if I use keypairs manually or use a ledger. But trezor support would be nice.
We have forked the app, you can find our version at https://stellarfish.org/ but the version with trezor support is only available on test.
I will try to extract the exact aobject being passed to trezor connect. One additional info: if I included the sender address as destionation, there was no Tresorconnect error, only the stellar network did not accept the signed package

**Comment by tsusanka** [comment] 2018-12-04 08:56
@lordcase Trezor One or Trezor T?

**Comment by lordcase** [comment] 2018-12-04 09:03
I'm using an One for testing

Tomas Susanka <notifications@github.com> ezt írta (időpont: 2018. dec. 4.,
K, 9:56):

**Comment by tsusanka** [comment] 2018-12-04 09:06
Aren't you calling CreateAccountOp before the ChangeTrustOp by any chance?

**Comment by tsusanka** [comment] 2018-12-04 09:06
(For reference: this might be connected to https://github.com/trezor/trezor-mcu/commit/b51f995da747a0630ae6eb298a0d0be3b5e05b08 )

**Comment by lordcase** [comment] 2018-12-04 09:25
No, actually looking at the code the only function that is being called
is stellarSignTransaction. The only difference is the parameters being
passed to it.

Tomas Susanka <notifications@github.com> ezt írta (időpont: 2018. dec. 4.,
K, 10:06):

**Comment by tsusanka** [comment] 2018-12-04 09:32
I mean if by any chance you're using more operations than one and one of them is ChangeTrust (or any other actually).

**Comment by lordcase** [comment] 2018-12-04 09:36
In this operation, no.

What happens is I log the user in (which is successful), and then in a
completely separate step I try to do the ChangeTrust operation.

There is one single call to TrezorConnect, which fails with the above error
without a destionation address in operations[0], succeeds with the source
address but then fails at another level (i suspect at the stellar network)

Tomas Susanka <notifications@github.com> ezt írta (időpont: 2018. dec. 4.,
K, 10:32):

**Comment by tsusanka** [comment] 2022-02-04 15:43
Thank you for your issue. There were many Stellar fixes in the past years so this is most likely fixed. Please reopen if this is not the case.

**Closed as completed by tsusanka** 2022-02-04 15:43 UTC
