### ISSUE TITLE
Support LTC/altcoins discovery

### ISSUE THREAD

**Issue by runn1ng** [trezor/connect#55] opened 2017-07-03 15:49 UTC
Connect doesn't support LTC / other BTC-based altcoins discovery

Again this will be harder to do because connect uses slightly outdated hd-wallet

**Comment by prusnak** [comment] 2017-07-04 15:10
Duplicate of https://github.com/trezor/connect/issues/45

**Closed by prusnak** 2017-07-04 15:10 UTC
