### ISSUE TITLE
Sign Ethereum message not working on TREZOR model T

### ISSUE THREAD

**Issue by janezkranjc** [trezor/connect#125] opened 2018-05-24 09:47 UTC
https://connect.trezor.io/4/examples/signmsg-ethereum.html

In the following example, no matter the message I get the error:
```
{
  "success": false,
  "error": "Unexpected message"
}
```

The popup opens for a second or so and then closes by itself.

**Comment by janezkranjc** [comment] 2018-05-24 09:47
I am using a TREZOR model T.

**Comment by prusnak** [comment] 2018-05-24 10:30
Duplicate of https://github.com/trezor/connect/issues/109

**Closed as completed** 2018-05-24 10:30 UTC
