### ISSUE TITLE
Config Too Old?

### ISSUE THREAD

**Issue by matiu** [trezor/connect#84] opened 2017-10-23 13:28 UTC
Copay Dev here.

Trying to export a public key using:
        TrezorConnect.getXPubKey(path, callback);

We get:
Uncaught (in promise) Error: Config too old; 1508764829 >= 1508601310
    at o (https://connect.trezor.io/1/popup/popup-dist.js:1030:891)
    at sendResponseAndClearCallback (extensions::messaging:417:9)
    at messageListener (extensions::messaging:449:11)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:140:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:140:26)
    at dispatchOnMessage (extensions::messaging:390:22)

Any ideas? This is currently happening to all Copay/Trezor users.

We are currently using TrezorConnect from bower.json:
```
    "trezor-connect": "https://github.com/trezor/connect.git#6797f60f3fd0ee4b3957a31700832cd7fdad6038",
```

**Comment by prusnak** [comment] 2017-10-23 13:31
Working on a fix. Also don't use Bower, it is obsolete.

**Comment by prusnak** [comment] 2017-10-23 14:02
Should be fixed, closing as duplicate of https://github.com/trezor/connect/issues/57

**Closed by prusnak** 2017-10-23 14:02 UTC

**Comment by matiu** [comment] 2017-10-23 14:08
thanks.
